import { Poppins } from "next/font/google";
import Nav from "@/app/(components)/Navbar/Nav";
import "./globals.css";
import MobileMenu from "./(components)/Navbar/components/MobileMenu";
import NavState from "./(components)/Navbar/context/NavContext";
import MobileMenuBackdrop from "./(components)/Navbar/components/MobileMenuBackdrop";
import Footer from "./(components)/Footer";

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={poppins.className}>
                <NavState>
                    <Nav />
                    <MobileMenu />
                    <MobileMenuBackdrop />
                </NavState>
                <main>{children}</main>
                <Footer />
            </body>
        </html>
    );
}
